### ISSUE TITLE
Response status code does not indicate success: 401 (Unauthorized).

### ISSUE THREAD

**Issue by nhendersn52** [okta/samples-aspnet#45]
I have downloaded the sample code and can run the app, but when I click the Log In button, I receive the error 'Response status code does not indicate success: 401 (Unauthorized).' I believe this is due to the okta:OktaDomain property, but I do not know how to solve this.

I set the property to https://companyname-dev-number.oktapreview.com/ but it results in the 401 error. I have seen conflicting information on what to set as the domain, whether or not to include the companyname or to take off the .com/. When I remove the .com/, I instead get 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'. I have tried every combination I can think of but I never get to the Okta Log In page.

**Comment by bryanapellanes-okta** [comment]
@nhendersn52 ,
Thank you for your inquiry.  The value to use for the `okta:OktaDomain` property is found on the dashboard tab when you log into the developer console.  You can sign into the developer console at `https://developer.okta.com` for production, or for your case, since you appear to be using okta preview, `https://developer.oktapreview.com`.  Once signed into the developer console, click the `Dashboard` tab and you will see your Okta domain in the upper right, see the following screenshot:
![image](https://user-images.githubusercontent.com/63638027/93500988-ae9f1e80-f8c9-11ea-999f-e381165d6d29.png)

When entered into your `web.config` file the line should look like the following, making sure to replace `dev-XXXXXX` with your appropriate value:
`<add key="okta:OktaDomain" value="https://dev-XXXXXX.oktapreview.com" />`

I hope this helps, comment here if you have further questions.
